name: NuGet Publish

on:
  release:
    types: [published, created, edited]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # This checks out the commit that triggered the workflow run

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Pack
        run: dotnet pack Cinlogic.Sync/Cinlogic.Sync.csproj --no-build --configuration Release /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} /p:CopyrightYear=$(date +%Y) --output out

      - name: Push
        run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
